### ISSUE TITLE
App crashes when share is triggered

### ISSUE THREAD

**Issue by dwitzig** [janumedia/SocialANE#1]
using the same example as the readme, app will crash and exit when this is triggered 

var socialAne:Social = Social.instance;
socialAne.share(subjectStr, messageStr);

**Comment by janumedia** [comment]
I just tested it again and working fine. Have you check perhaps file . ANE you downloaded is corrupted? 
The best way to check the problem is check in eclipse LogCat

**Comment by dwitzig** [comment]
Hi Janumedia, thanks for getting back to me. turns out the ANE is fine.
I was triggering NativeApplication.nativeApplication.exit(); on stage deactivate 
and I did not realise the share feature was deactivating the stage.

**Comment by janumedia** [comment]
ah sure, NativeApplication.nativeApplication.exit(); usually set in default AIR template
